### ISSUE TITLE
ImportError: cannot import name 'create_task

### ISSUE THREAD

**Issue by Draco-Zero** [Hornwitser/FactorioUpbot#1]
How do I deal with this error at startup?
`root@dracoblog:~/FactorioUpbot# python3 launch.py
Traceback (most recent call last):
  File "launch.py", line 5, in <module>
    from bot import FactorioUpbot, prefixes
  File "/root/FactorioUpbot/bot.py", line 1, in <module>
    from asyncio import create_task
ImportError: cannot import name 'create_task'
`

**Comment by Hornwitser** [comment]
This bot requires Python 3.7 or greater to function.

**Comment by Draco-Zero** [comment]
The server has version 3.7 installed. if you run python3.7 launch.py:
`Traceback (most recent call last):
  File "launch.py", line 3, in <module>
    from discord.ext.commands import Bot
ModuleNotFoundError: No module named 'discord'
`

**Comment by Hornwitser** [comment]
I'm not sure what you expect out of an unlicensed and undocumented personal project.  But if you can't make it run on your own I'm afraid I can't help you.
